/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness Check */
        get: operations["readiness_check_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_api_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stocks */
        get: operations["list_stocks_api_stocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stock */
        get: operations["get_stock_api_stocks__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnnualFinancialInput */
        AnnualFinancialInput: {
            /** Fiscalyear */
            fiscalYear: number;
            /**
             * Periodend
             * Format: date
             */
            periodEnd: string;
            /** Netincomecommon */
            netIncomeCommon: string | null;
            /** Ebit */
            ebit: string | null;
            /** Pretaxincome */
            preTaxIncome: string | null;
            /** Incometaxexpense */
            incomeTaxExpense: string | null;
            /** Commonequity */
            commonEquity: string | null;
            /** Interestbearingdebt */
            interestBearingDebt: string | null;
            /** Cashandequivalents */
            cashAndEquivalents: string | null;
            /** Totalliabilities */
            totalLiabilities: string | null;
            /** Interestexpense */
            interestExpense: string | null;
            /** Cfo */
            cfo: string | null;
            /** Capex */
            capex: string | null;
            /** Interestpaid */
            interestPaid: string | null;
            interestPaidClassification: components["schemas"]["InterestPaidClassification"];
            /** Dilutedeps */
            dilutedEps: string | null;
            /** Dilutedshares */
            dilutedShares: string | null;
        };
        /**
         * Applicability
         * @enum {string}
         */
        Applicability: "ALL" | "NON_FINANCIAL";
        /** BenchmarkPointInput */
        BenchmarkPointInput: {
            /**
             * Periodend
             * Format: date
             */
            periodEnd: string;
            /** Indexvalue */
            indexValue: string | null;
        };
        /** CapitalActionEvaluationDTO */
        CapitalActionEvaluationDTO: {
            /**
             * Ruleid
             * @default capital_action_flag
             * @constant
             */
            ruleId: "capital_action_flag";
            /**
             * Category
             * @default REVIEW
             * @constant
             */
            category: "REVIEW";
            status: components["schemas"]["CapitalActionStatus"];
            /** Historyyears */
            historyYears: (5 | 3 | 1) | null;
            /** Periodstart */
            periodStart: string | null;
            /** Periodend */
            periodEnd: string | null;
            /** Metrics */
            metrics: components["schemas"]["MetricValueDTO"][];
            /** Reasoncodes */
            reasonCodes: components["schemas"]["ReasonCode"][];
            /** Warnings */
            warnings: string[];
        };
        /**
         * CapitalActionStatus
         * @enum {string}
         */
        CapitalActionStatus: "REVIEW_DILUTION" | "STABLE" | "REVIEW_BUYBACK_PRICE" | "N/A";
        /**
         * Confidence
         * @enum {string}
         */
        Confidence: "HIGH" | "MEDIUM" | "LOW";
        /**
         * CoreStatus
         * @enum {string}
         */
        CoreStatus: "PASS" | "HOLD" | "FAIL" | "N/A";
        /**
         * Currency
         * @enum {string}
         */
        Currency: "USD" | "KRW";
        /** CurrentMarketInput */
        CurrentMarketInput: {
            /**
             * Asof
             * Format: date-time
             */
            asOf: string;
            /** Currentprice */
            currentPrice: string | null;
            /** Marketcap */
            marketCap: string | null;
            /** Dilutedshares */
            dilutedShares: string | null;
            /** Riskfreerate */
            riskFreeRate: string | null;
        };
        /** DcfResultDTO */
        DcfResultDTO: {
            status: components["schemas"]["ValuationStatus"];
            /**
             * Method
             * @default OWNER_EARNINGS_DCF
             * @constant
             */
            method: "OWNER_EARNINGS_DCF";
            /** Historyyears */
            historyYears: (5 | 3 | 1) | null;
            /** Normalizedownerearnings */
            normalizedOwnerEarnings: number | null;
            /** Normalizedoeps */
            normalizedOeps: number | null;
            /** Rawgrowth */
            rawGrowth: number | null;
            /** Growthcap */
            growthCap: number | null;
            /** Basegrowth */
            baseGrowth: number | null;
            /** Discountrate */
            discountRate: number | null;
            scenarios: components["schemas"]["DcfScenariosDTO"] | null;
            /** Currentprice */
            currentPrice: number | null;
            /** Conservativemarginofsafety */
            conservativeMarginOfSafety: number | null;
            confidence: components["schemas"]["Confidence"];
            /** Reasoncodes */
            reasonCodes: components["schemas"]["ReasonCode"][];
            /** Warnings */
            warnings: string[];
        };
        /** DcfScenarioDTO */
        DcfScenarioDTO: {
            /** Growthrate */
            growthRate: number;
            /** Terminalgrowthrate */
            terminalGrowthRate: number;
            /** Intrinsicvaluepershare */
            intrinsicValuePerShare: number;
        };
        /** DcfScenariosDTO */
        DcfScenariosDTO: {
            conservative: components["schemas"]["DcfScenarioDTO"];
            base: components["schemas"]["DcfScenarioDTO"];
            optimistic: components["schemas"]["DcfScenarioDTO"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /**
         * IndustryType
         * @enum {string}
         */
        IndustryType: "GENERAL" | "FINANCIAL";
        /**
         * InterestPaidClassification
         * @enum {string}
         */
        InterestPaidClassification: "CFO" | "NON_CFO" | "UNKNOWN";
        /**
         * Market
         * @enum {string}
         */
        Market: "NASDAQ" | "NYSE" | "KOSPI" | "KOSDAQ";
        /**
         * MetricUnit
         * @enum {string}
         */
        MetricUnit: "RATIO" | "MULTIPLE" | "CURRENCY" | "COUNT";
        /** MetricValueDTO */
        MetricValueDTO: {
            /** Metricid */
            metricId: string;
            /** Value */
            value: number | null;
            unit: components["schemas"]["MetricUnit"];
            specialValue?: components["schemas"]["SpecialValue"] | null;
        };
        /** QuarterlyBookPriceInput */
        QuarterlyBookPriceInput: {
            /** Fiscalyear */
            fiscalYear: number;
            /** Fiscalquarter */
            fiscalQuarter: number;
            /**
             * Periodend
             * Format: date
             */
            periodEnd: string;
            /** Adjustedcloseprice */
            adjustedClosePrice: string | null;
            /** Bvps */
            bvps: string | null;
        };
        /**
         * ReadinessReason
         * @enum {string}
         */
        ReadinessReason: "DATABASE_NOT_CONFIGURED" | "DATABASE_UNAVAILABLE" | "NO_LIVE_SNAPSHOTS" | "MARKET_DATA_PUBLICATION_DISABLED";
        /** ReadinessResponse */
        ReadinessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
            /** Databaseconnected */
            databaseConnected: boolean;
            /** Livesnapshotcount */
            liveSnapshotCount: number;
            /** Marketdatapublicationenabled */
            marketDataPublicationEnabled: boolean;
            /** Reasons */
            reasons: components["schemas"]["ReadinessReason"][];
        };
        /**
         * ReasonCode
         * @enum {string}
         */
        ReasonCode: "FINANCIAL_SECTOR" | "MISSING_DATA" | "INSUFFICIENT_HISTORY" | "NON_POSITIVE_DENOMINATOR" | "INVALID_TAX_RATE" | "NON_POSITIVE_START_VALUE" | "UNKNOWN_INTEREST_CLASSIFICATION" | "PREREQUISITE_FAILED";
        /**
         * RuleDefinitionCategory
         * @enum {string}
         */
        RuleDefinitionCategory: "CORE" | "AUXILIARY" | "REVIEW" | "VALUATION";
        /** RuleDefinitionDTO */
        RuleDefinitionDTO: {
            /** Ruleid */
            ruleId: string;
            /** Name */
            name: string;
            category: components["schemas"]["RuleDefinitionCategory"];
            /** Defaultthresholds */
            defaultThresholds: components["schemas"]["RuleThresholdDTO"][];
            applicability: components["schemas"]["Applicability"];
            /** Supportedhistoryyears */
            supportedHistoryYears: (5 | 3 | 1)[];
        };
        /** RuleEvaluationDTO */
        RuleEvaluationDTO: {
            /** Ruleid */
            ruleId: string;
            /**
             * Category
             * @enum {string}
             */
            category: "CORE" | "AUXILIARY";
            status: components["schemas"]["RuleStatus"];
            /** Historyyears */
            historyYears: (5 | 3 | 1) | null;
            /** Periodstart */
            periodStart: string | null;
            /** Periodend */
            periodEnd: string | null;
            /** Metrics */
            metrics: components["schemas"]["MetricValueDTO"][];
            /** Reasoncodes */
            reasonCodes: components["schemas"]["ReasonCode"][];
            /** Warnings */
            warnings: string[];
        };
        /** RuleListResponse */
        RuleListResponse: {
            /** Items */
            items: components["schemas"]["RuleDefinitionDTO"][];
        };
        /**
         * RuleStatus
         * @enum {string}
         */
        RuleStatus: "PASS" | "FAIL" | "N/A";
        /** RuleThresholdDTO */
        RuleThresholdDTO: {
            /** Metricid */
            metricId: string;
            operator: components["schemas"]["ThresholdOperator"];
            /** Value */
            value: number;
            unit: components["schemas"]["MetricUnit"];
        };
        /**
         * SortOrder
         * @enum {string}
         */
        SortOrder: "asc" | "desc";
        /**
         * SourceType
         * @enum {string}
         */
        SourceType: "FIXTURE" | "LIVE";
        /**
         * SpecialValue
         * @enum {string}
         */
        SpecialValue: "INFINITY";
        /** StockDetailDTO */
        StockDetailDTO: {
            /** Id */
            id: string;
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            market: components["schemas"]["Market"];
            /** Sector */
            sector: string;
            currency: components["schemas"]["Currency"];
            /** Currentprice */
            currentPrice: number | null;
            /** Marketcap */
            marketCap: number | null;
            coreStatus: components["schemas"]["CoreStatus"];
            /** Corepasscount */
            corePassCount: number;
            /** Corefailcount */
            coreFailCount: number;
            /** Corenacount */
            coreNaCount: number;
            valuationStatus: components["schemas"]["ValuationStatus"];
            /** Conservativeintrinsicvalue */
            conservativeIntrinsicValue: number | null;
            /** Conservativemarginofsafety */
            conservativeMarginOfSafety: number | null;
            confidence: components["schemas"]["Confidence"];
            /**
             * Dataasof
             * Format: date-time
             */
            dataAsOf: string;
            sourceType: components["schemas"]["SourceType"];
            /**
             * Lastsuccessfulat
             * Format: date-time
             */
            lastSuccessfulAt: string;
            /** Isstale */
            isStale: boolean;
            industryType: components["schemas"]["IndustryType"];
            /** Sourcename */
            sourceName: string;
            /** Annualfinancials */
            annualFinancials: components["schemas"]["AnnualFinancialInput"][];
            /** Quarterlybookprices */
            quarterlyBookPrices: components["schemas"]["QuarterlyBookPriceInput"][];
            /** Benchmarkpoints */
            benchmarkPoints: components["schemas"]["BenchmarkPointInput"][];
            currentMarket: components["schemas"]["CurrentMarketInput"];
            /** Ruleevaluations */
            ruleEvaluations: components["schemas"]["RuleEvaluationDTO"][];
            capitalAction: components["schemas"]["CapitalActionEvaluationDTO"];
            dcf: components["schemas"]["DcfResultDTO"];
            /** Warnings */
            warnings: string[];
        };
        /** StockListResponse */
        StockListResponse: {
            /** Items */
            items: components["schemas"]["StockSummaryDTO"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * StockSort
         * @enum {string}
         */
        StockSort: "ticker" | "currentPrice" | "marketCap" | "conservativeMarginOfSafety" | "corePassCount";
        /** StockSummaryDTO */
        StockSummaryDTO: {
            /** Id */
            id: string;
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            market: components["schemas"]["Market"];
            /** Sector */
            sector: string;
            currency: components["schemas"]["Currency"];
            /** Currentprice */
            currentPrice: number | null;
            /** Marketcap */
            marketCap: number | null;
            coreStatus: components["schemas"]["CoreStatus"];
            /** Corepasscount */
            corePassCount: number;
            /** Corefailcount */
            coreFailCount: number;
            /** Corenacount */
            coreNaCount: number;
            valuationStatus: components["schemas"]["ValuationStatus"];
            /** Conservativeintrinsicvalue */
            conservativeIntrinsicValue: number | null;
            /** Conservativemarginofsafety */
            conservativeMarginOfSafety: number | null;
            confidence: components["schemas"]["Confidence"];
            /**
             * Dataasof
             * Format: date-time
             */
            dataAsOf: string;
            sourceType: components["schemas"]["SourceType"];
            /**
             * Lastsuccessfulat
             * Format: date-time
             */
            lastSuccessfulAt: string;
            /** Isstale */
            isStale: boolean;
        };
        /**
         * ThresholdOperator
         * @enum {string}
         */
        ThresholdOperator: "GTE" | "LTE" | "GT" | "LT";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ValuationStatus
         * @enum {string}
         */
        ValuationStatus: "PASS_WITH_MARGIN" | "WATCH" | "NO_MARGIN" | "N/A";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness_check_readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    list_rules_api_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleListResponse"];
                };
            };
        };
    };
    list_stocks_api_stocks_get: {
        parameters: {
            query?: {
                search?: string | null;
                market?: components["schemas"]["Market"] | null;
                sector?: string | null;
                coreStatus?: components["schemas"]["CoreStatus"] | null;
                valuationStatus?: components["schemas"]["ValuationStatus"] | null;
                sort?: components["schemas"]["StockSort"];
                order?: components["schemas"]["SortOrder"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stock_api_stocks__ticker__get: {
        parameters: {
            query?: {
                market?: components["schemas"]["Market"] | null;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockDetailDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
