import { FilterRuleDefinition, RulePreset } from '../types/rules';

export const DEFAULT_BUFFETT_RULES: FilterRuleDefinition[] = [
  {
    id: 'roe_5yr',
    category: 'PROFITABILITY',
    name: '5Y Avg ROE',
    summary: '최근 5개년 연속 자기자본이익률(ROE)이 기준치를 상회하는지 검증합니다.',
    description: '워런 버핏은 기업의 규모보다 투입된 자기자본 대비 얼마의 순이익을 창출하는지(ROE >= 15%)를 가장 중요한 자본 효율성 지표로 평가합니다.',
    evaluationPeriod: '최근 5개년',
    controlType: 'slider',
    defaultValue: 15,
    currentValue: 15,
    min: 5,
    max: 40,
    step: 1,
    unit: '%',
    comparator: 'gte',
    isCoreBuffettRule: true,
  },
  {
    id: 'roic_5yr',
    category: 'PROFITABILITY',
    name: '5Y Avg ROIC',
    summary: '투입 자본 대비 실질 영업이익 창출력(ROIC)을 검증합니다.',
    description: '부채 레버리지 착시를 제거하고, 실제 영업활동에 투입된 총자본(IC)으로부터 세후영업이익(NOPAT)을 창출하는 본원적 경쟁력을 평가합니다.',
    evaluationPeriod: '최근 5개년',
    controlType: 'slider',
    defaultValue: 10,
    currentValue: 10,
    min: 5,
    max: 30,
    step: 1,
    unit: '%',
    comparator: 'gte',
    isCoreBuffettRule: true,
  },
  {
    id: 'eps_cagr_5yr',
    category: 'GROWTH',
    name: '5Y EPS CAGR',
    summary: '주당순이익(EPS)의 연평균 복리 성장률(CAGR)이 시장 평균을 초과하는지 평가합니다.',
    description: '단순 외형 성장이 아닌 주당 내재가치의 복리 증가 속도를 측정하며, 최소 10% 이상의 연평균 EPS 성장을 요구합니다.',
    evaluationPeriod: '최근 5개년',
    controlType: 'slider',
    defaultValue: 10,
    currentValue: 10,
    min: 0,
    max: 30,
    step: 1,
    unit: '%',
    comparator: 'gte',
    isCoreBuffettRule: true,
  },
  {
    id: 'one_dollar_test',
    category: 'SHAREHOLDER_VALUE',
    name: '$1 Retained Test',
    summary: '기업이 사내에 유보한 이익 1달러당 주주에게 1달러 이상의 시장가치를 창출했는지 검증합니다.',
    description: '버핏의 소유주 관련 사업 원칙: (5개년 시가총액 증가분 / 5개년 누적 유보이익 >= 1.0). 유보이익이 주주가치로 이어지지 않는 비효율적 기업을 철저히 배제합니다.',
    evaluationPeriod: '최근 5개년',
    controlType: 'toggle',
    defaultValue: true,
    currentValue: true,
    comparator: 'eq',
    isCoreBuffettRule: true,
  },
  {
    id: 'debt_to_equity',
    category: 'SAFETY',
    name: 'Debt-to-Equity',
    summary: '자기자본 대비 과도한 부채와 차입금에 의존하지 않는 안전한 재무구조인지 검증합니다.',
    description: '버핏은 차입금 레버리지로 만든 일시적 고수익을 경계하며, 부채총계/자본총계 80~100% 이하의 건전한 무차입/저차입 기업을 선호합니다.',
    evaluationPeriod: '최근 분기',
    controlType: 'slider',
    defaultValue: 80,
    currentValue: 80,
    min: 20,
    max: 200,
    step: 10,
    unit: '%',
    comparator: 'lte',
    isCoreBuffettRule: true,
  },
  {
    id: 'share_dilution',
    category: 'SHAREHOLDER_VALUE',
    name: 'No Share Dilution',
    summary: '무분별한 유상증자나 주식발행으로 기존 주주가치를 희석시키지 않았는지 검증합니다.',
    description: '최근 5개년 발행주식수 증가율(CAGR)이 0% 이하(자사주 매입/소각 진행)인 기업을 선별하여 기존 주주의 소유 지분 가치를 보호합니다.',
    evaluationPeriod: '최근 5개년',
    controlType: 'toggle',
    defaultValue: true,
    currentValue: true,
    comparator: 'eq',
    isCoreBuffettRule: true,
  },
  {
    id: 'interest_coverage',
    category: 'SAFETY',
    name: 'Interest Coverage',
    summary: '영업이익으로 이자비용을 충분히 감당할 수 있는지 지급 능력을 평가합니다.',
    description: '영업이익 / 이자비용 >= 5.0배 이상 유지 여부를 검증하여 고금리 및 경기 침체 환경에서도 안전한 방어력을 갖추었는지 확인합니다.',
    evaluationPeriod: '최근 1개년',
    controlType: 'slider',
    defaultValue: 5.0,
    currentValue: 5.0,
    min: 2.0,
    max: 20.0,
    step: 0.5,
    unit: 'x',
    comparator: 'gte',
    isCoreBuffettRule: false,
  },
  {
    id: 'benchmark_bps_outperformance',
    category: 'GROWTH',
    name: 'Benchmark Alpha',
    summary: '순자산가치(BPS) 증가율이 시장 지수(S&P 500 / KOSPI) 수익률을 초과하는지 평가합니다.',
    description: '장부상 순자산의 복리 축적 속도가 시장 지수 평균을 초과하는 진정한 초과 수익 기업을 선별합니다.',
    evaluationPeriod: '최근 5개년',
    controlType: 'toggle',
    defaultValue: true,
    currentValue: true,
    comparator: 'eq',
    isCoreBuffettRule: false,
  }
];

export const RULE_PRESETS: RulePreset[] = [
  {
    id: 'buffett_rules',
    name: 'Buffett Rules',
    badge: 'Buffett Rules',
    description: '버핏의 6대 핵심 원칙(ROE 15%, ROIC 10%, EPS CAGR 10%, 1달러 테스트 통과, 부채비율 80% 이하, 주식수 희석 방지)을 모두 만족하는 초우량 기업',
    filterValues: {
      roe_5yr: 15,
      roic_5yr: 10,
      eps_cagr_5yr: 10,
      one_dollar_test: true,
      debt_to_equity: 80,
      share_dilution: true,
      interest_coverage: 5.0,
      benchmark_bps_outperformance: true,
    }
  }
];
